default['fai_linux_sysedge']['src_url'] = 'http://s1.fujitsucanada.net/downloads/Linux_x86_58.tar.gz'
default['fai_linux_sysedge']['src_url_v59'] = 'http://s1.fujitsucanada.net/downloads/Linux_x86_59.tar.gz'
default['fai_linux_sysedge']['download_dir'] = '/tmp'
default['fai_linux_sysedge']['target_dir'] = '/tmp/sysedge'
default['fai_linux_sysedge']['snmp_read'] = 'C@unicenter3'
default['fai_linux_sysedge']['upgrade'] = 'false'
default['fai_linux_sysedge']['version'] = '59'
default['fai_linux_sysedge']['force'] = 'false'
